FROM node:20.9.0-alpine as build

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

RUN yarn run build

FROM node:20.9.0-alpine

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/yarn.lock ./yarn.lock

RUN yarn install --production

RUN npx update-browserslist-db@latest

EXPOSE 4173

CMD ["yarn", "run", "preview", "--host", "0.0.0.0", "--port", "4173"]