FROM node:18-slim

RUN mkdir -p /usr/src/app

RUN apt-get update -y && apt-get install -y openssl

WORKDIR /usr/src/app

COPY --chown=node:node package*.json ./
COPY --chown=node:node yarn.lock ./
COPY --chown=node:node dist/ ./dist/
COPY --chown=node:node vite.config.ts ./

ENV NODE_ENV=production
ENV LOGGER_MODE=filesystem
RUN yarn install

EXPOSE 3000

CMD ["yarn", "run", "preview"]