version: '3.8'

services:
  database:
    image: postgres:14.3
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel_docker
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    networks:
        - laravel

  nginx:
      build:
          context: .
          dockerfile: nginx.dockerfile
      depends_on:
          - php
          - database
      container_name: nginx
      ports:
          - 80:80
          - 443:443
      volumes:
          - ./src:/var/www/html
      networks:
          - laravel
  php:
      build:
          context: .
          dockerfile: php.dockerfile
      container_name: php
      volumes:
          - ./src:/var/www/html
      networks:
          - laravel

  # artisan:
  #     build:
  #         context: .
  #         dockerfile: php.dockerfile
  #     container_name: artisan
  #     volumes:
  #         - ./src:/var/www/html
  #     working_dir: /var/www/html
  #     entrypoint: ['php', 'artisan']
  #     networks:
  #         - laravel

  # npm:
  #     image: node:current-alpine
  #     container_name: npm
  #     volumes:
  #         - ./src:/var/www/html
  #     working_dir: /var/www/html
  #     entrypoint: ['npm']
  #     networks:
  #         - laravel
volumes:
  db-data:

networks:
    laravel:
        name: laravel