version: '3.8'

services:
  database:
    image: postgres:14.3
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel_docker
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    networks:
      - laravel

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - database
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
    command: yarn run dev
    depends_on:
      - backend
    networks:
      - laravel

volumes:
  db-data:

networks:
  laravel:
    name: laravel
