version: '3.8'

services:
  database:
    image: mysql:8
    container_name: database
    ports:
      - 3304:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}  
    networks:
      - laravel

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - database
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
    command: yarn run dev
    depends_on:
      - backend
    networks:
      - laravel

volumes:
  db-data:

networks:
  laravel:
    name: laravel
